### ISSUE TITLE
[4.6.0] Bug: <describe issue>

### ISSUE THREAD

**Issue by clevemcmillan** [hirosystems/stacks-wallet#1092] opened 2022-06-26 06:26 UTC
Bug found testing Hiro Wallet build undefined, 4.6.0.

Hi, just trying to transfer from blockstak to  STX but the transfer has been sitting there suspended for about 20 minutes so i gather it's not happening. 
Any advice?:

https://markuphero.com/share/pUuZNEoA9NCs3PAIYDWI

System: Mac 12.2
https://markuphero.com/share/iLFZSMHQ7KcX5dwb5VwQ

Browser: Chrome Version 102.0.5005.115 (Official Build) (x86_64)
https://markuphero.com/share/JTrgEO5a56bJWzEP9e55

Blockstack access on chrome: 
Stx opened on both Hiro desktop and Stx desktop

Took the receiving address from Stx and added it to the send in Blockstack, hit transfer all and nothing! 

thanks

**Comment by clevemcmillan** [comment] 2022-06-26 06:32
I also took a look here but have no idea what these represent?
![screencapture-explorer-stacks-co-transactions-2022-06-25-23_28_33](https://user-images.githubusercontent.com/49096342/175802533-18b3f5ad-816e-487e-b26d-0f8383700e8a.png)
![screencapture-explorer-stacks-co-transactions-2022-06-25-23_29_41](https://user-images.githubusercontent.com/49096342/175802535-efcc9804-dd29-45e9-bc5e-0015d6b3ae1d.png)

**Comment by clevemcmillan** [comment] 2022-06-26 06:43
![CleanShot 2022-06-25 at 23 41 34](https://user-images.githubusercontent.com/49096342/175802762-3138fe75-88ef-4595-8cdf-e8b6b499d56e.png)


just updated the Hiro software and refreshed the blockstack page and began taking a second stable at it and have this error now but as usual with all these blockchain errors, there is no context to what, when, why how, who and what 'to do'.

**Comment by clevemcmillan** [comment] 2022-06-26 06:51
![CleanShot 2022-06-25 at 23 49 54](https://user-images.githubusercontent.com/49096342/175803003-faaf5e9e-1699-4c74-8144-bfb352ba1756.png)



spotted this in the event it has anything to do with it?

**Comment by clevemcmillan** [comment] 2022-06-26 06:53
thats all I got. 
one day, who ever these kids are behind this entire blockchain crapolla will get a cohesive method for which to use it and trade with it. Till then, it's going to go thru struggle town. coz I'm yet to have an experience with BC and any related coin of sorts that is worth bringing up when conversing with others that is spoken of in a positive light.

**Comment by fbwoolf** [comment] 2022-06-26 12:52
I am not real familiar with the deprecated wallet you are using, but it looks to me like you are trying to send BTC to a STX address? That won't work. Try sending the BTC to a BTC address?

**Comment by clevemcmillan** [comment] 2022-06-26 14:00
ok thanks, so i just pick another wallet that has  BC then go from there to
STX?

**Comment by fbwoolf** [comment] 2022-06-26 19:26
I am going to close this issue bc it is not a bug in our wallet. Please join our Discord server if you need to connect with people in the community for questions/support.

**Closed by fbwoolf** 2022-06-26 19:26 UTC
