### ISSUE TITLE
[4.6.1] Bug: Transaction Pending more than 24 hrs.

### ISSUE THREAD

**Issue by enjoywithouthey** [hirosystems/stacks-wallet#1072] opened 2022-04-02 12:06 UTC
Hi Hiro,

I accidently double-claimed rewards from Alex Staking Pool. The second transaction (which has the same nonce of 488) has been pending for 24 hours now.

Any guidance to remedy this?

Confirmed txid: 0x2d44d806a3b6b59eef34c0a83c6f28acab8891a884975d9339e58bc15c3f1a7c
Pending/Stuck txid: 0x9a29638a15c334c966bbf37961ffb39224d74b9cdb55f0ea02718f3d9e18697a

thank you so much,

-Justin

Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by fbwoolf** [comment] 2022-04-02 16:34
This is not a bug 😄  ...and this is the repo for the desktop wallet. Unfortunately, you just have to wait for the tx to fail. It will, but the exact time cannot be predicted. I am closing this issue bc it is not a bug in the wallet. If you need more support on this, the best place to ask is in Discord #support channel.

**Closed by fbwoolf** 2022-04-02 16:34 UTC
